# Generated by Django 2.0 on 2017-12-19 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sx_h_lie', models.IntegerField()),
                ('sx_h_liang', models.IntegerField()),
                ('sx_k_lie', models.IntegerField()),
                ('sx_k_liang', models.IntegerField()),
                ('xx_h_lie', models.IntegerField()),
                ('xx_h_liang', models.IntegerField()),
                ('xx_k_lie', models.IntegerField()),
                ('xx_k_liang', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('side', models.CharField(max_length=255)),
                ('line', models.CharField(max_length=100)),
                ('warning_type', models.CharField(max_length=255)),
                ('pic', models.FileField(blank=True, upload_to='upload/')),
                ('algo', models.ManyToManyField(to='test2web.Algo')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2web.Kind')),
                ('reason', models.ManyToManyField(blank=True, to='test2web.Reason')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2web.Site')),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2web.Site'),
        ),
    ]
