# Generated by Django 2.0 on 2017-12-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2web', '0002_auto_20171215_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='pic',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
