# Generated by Django 2.0 on 2017-12-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2web', '0004_auto_20171215_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='pic',
            field=models.FileField(blank=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='reason',
            field=models.ManyToManyField(blank=True, to='test2web.Reason'),
        ),
    ]
